name: Auto Refresh Push

on:
  schedule:
    - cron: '0 */6 * * *' # 每天0点推送
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main


      - name: Update README
        run: |
          echo "Update time - $(date +"%Y-%m-%d %H:%M:%S")" >> refresh.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto Refresh Push - $(date +"%Y-%m-%d %H:%M:%S")"
          git push